name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  BUILD_TYPE: Release

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      name: ${{ github.event.repository.name }}-${{ github.ref_name }}-ubuntu-amd64.tar.gz
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Release build os - ubuntu
        run: |
          chmod +x ci/release-build.sh
          ./ci/release-build.sh ubuntu ${{ env.BUILD_TYPE }} -xe

      - name: Calculate checksum and rename binary
        shell: bash
        run: |
          cd build/
          chmod +x ${{ github.event.repository.name }}
          tar -zcvf ${{ env.name }} ${{ github.event.repository.name }}
          echo $(shasum -a 256 ${{ env.name }} | cut -f1 -d' ') > ${{ env.name }}.sha256sum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}
          path: build/${{ env.name }}

      - name: Upload checksum of artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}.sha256sum
          path: build/${{ env.name }}.sha256sum

  centos:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    env:
      name: ${{ github.event.repository.name }}-${{ github.ref_name }}-centos-amd64.tar.gz
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Release build os - centos
        run: |
          chmod +x ci/release-build.sh
          ./ci/release-build.sh centos ${{ env.BUILD_TYPE }} -xe

      - name: Calculate checksum and rename binary
        shell: bash
        run: |
          cd build/
          chmod +x ${{ github.event.repository.name }}
          tar -zcvf ${{ env.name }} ${{ github.event.repository.name }}
          echo $(shasum -a 256 ${{ env.name }} | cut -f1 -d' ') > ${{ env.name }}.sha256sum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}
          path: build/${{ env.name }}

      - name: Upload checksum of artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}.sha256sum
          path: build/${{ env.name }}.sha256sum

  macos:
    runs-on: macos-latest
    env:
      name: ${{ github.event.repository.name }}-${{ github.ref_name }}-macos-amd64.tar.gz
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Release build os - macos
        run: |
          chmod +x ci/release-build.sh
          ./ci/release-build.sh macos ${{ env.BUILD_TYPE }} -xe

      - name: Calculate checksum and rename binary
        shell: bash
        run: |
          cd build/
          chmod +x ${{ github.event.repository.name }}
          tar -zcvf ${{ env.name }} ${{ github.event.repository.name }}
          echo $(shasum -a 256 ${{ env.name }} | cut -f1 -d' ') > ${{ env.name }}.sha256sum

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}
          path: build/${{ env.name }}

      - name: Upload checksum of artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}.sha256sum
          path: build/${{ env.name }}.sha256sum

  release:
    name: Release artifacts
    needs: [ ubuntu,centos,macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            **/${{ github.event.repository.name }}-*
